version:  "3"
services:
  hub:
    image:  selenium/hub:3.14
    ports:
      - 4444:4444
  chrome:
    image:  selenium/node-chrome:3.14
    environment:
      - HUB_HOST=hub
    depends_on:
      - hub
  firefox:
    image:  selenium/node-firefox:3.14
    environment:
      - HUB_HOST=hub
    depends_on:
      - hub
  search-module:
    image: himanshu/selenium-docker
    shm_size: "1gb"
    environment:
      - HUB_HOST=hub
      - MODULE=search-module.xml
      - BROWSER=firefox
    depends_on:
      - chrome
      - firefox
    volumes:
      - /Users/himarora1/dockerPractice/dockerCI/output/search-results1:/usr/share/udemy/test-output
  search-module2:
    image: himanshu/selenium-docker
    environment:
      - HUB_HOST=hub
      - MODULE=search-module.xml
      - BROWSER=chrome
    depends_on:
      - chrome
      - firefox
    volumes:
      - /Users/himarora1/dockerPractice/dockerCI/output/search-results2:/usr/share/udemy/test-output
  # book-flight-module:
  #   image: himanshu/selenium-docker
  #   shm_size: "1gb"
  #   environment:
  #     - HUB_HOST=hub
  #     - MODULE=book-flight-module.xml
  #     - BROWSER=chrome
  #   depends_on:
  #     - chrome
  #     - firefox
  #   volumes:
  #     - /Users/himarora1/IdeaProjects/docker/book-results1:/usr/share/udemy/test-output
  book-flight-module:
    image: himanshu/selenium-docker
    environment:
      - HUB_HOST=hub
      - MODULE=book-flight-module.xml
      - BROWSER=chrome
    depends_on:
      - chrome
      - firefox
    volumes:
      - /Users/himarora1/IdeaProjects/docker/book-results2:/usr/share/udemy/test-output
  